version: "3.9"

services:
  postgres:
    image: postgres:13.6-alpine
    container_name: multitenant-postgres
    ports:
      - "35432:5432"
    environment:
      POSTGRES_DB: MULTITENANT
      POSTGRES_USER: multitenant
      POSTGRES_PASSWORD: geheim
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:

